DNSレコード：SPF、DKIM、DMARCの基礎
mseninc/blog pull request #349
Opened 2024-10-18 01:48 UTC by Lee-juNu

レーザー学会のメールサーバー移行の件で初めて DNS レコードを学びながら整理していた内容を記事として書いてみました。

2024-10-20 04:37 UTC, junya-gera reviewed
気になった部分にコメント入れました。内容あまり詳しくないので違ったらすみません。あと全体的に半角の後に半角スペースがない部分があるので確認お願いします。

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +### 昔はただのコメントの役わり
```suggestion
### 昔はただのコメントの役割
```

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +本来の TXT レコードは人が読めるノートを入力する用途だったらしいです。昔の TXT レコードはコーディングするときのコメント見たいな説明を目的としていたイメージですね。
```suggestion
本来の TXT レコードは人が読めるノートを入力する用途だったらしいです。昔の TXT レコードはコーディングするときのコメントみたいな説明を目的としていたイメージですね。
```

「～のような」という意味の「～みたいな」のときは「見る」ではないのでひらがなです。

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +> 現在、DNS TXTレコードの最も重要な使用用途は、メールのスパム防止とドメイン所有権の確認ですが、TXTレコードはもともとこれらの用途のために設計されたものではありません。
引用元を記載してください (https://github.com/mseninc/blog の「引用について」参照) 。

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> + SPF や DKIMと併用することで送信認証をより強固にし、なりすましなどを防ぐしくみです。 DMARC では、SPF や DKIM と組み合わせて、認証が失敗したときにバウンスさせるかスパムフォルダーに入れるかなおの振る舞いを設定します。
```suggestion
 SPF や DKIMと併用することで送信認証をより強固にし、なりすましなどを防ぐしくみです。 DMARC では、SPF や DKIM と組み合わせて、認証が失敗したときにバウンスさせるかスパムフォルダーに入れるかなどの振る舞いを設定します。
```
なお → など？

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +メールサーバー移行の件を聞いてメールサーバーを一度見てみたいと思いました案件をもらった後に調べている途中一番多く振れたのはこの DNS レコードでした。さすがまだ知らないパソコンの知識を学ぶことは楽しいですね。また別の知識を持ってきます。
```suggestion
メールサーバー移行の件を聞いてメールサーバーを一度見てみたいと思いました。案件をもらった後に調べている途中一番多く触れたのはこの DNS レコードでした。さすがまだ知らないパソコンの知識を学ぶことは楽しいですね。また別の知識を持ってきます。
```

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +### DNS SPF とは？
内容は SPF レコードについてだと思うので「SPF レコードとは？」のほうが良さそう？
なので SPF の説明も別であるほうがいいかもです (DKIM のほうは DKIM 自体の説明があるので)。

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +SPF TXT レコードは特定ドメインからのメール送信が許されたすべてのサーバーをリスト化した一種の DNS TXTレコードです。
```suggestion
SPF TXT レコードは特定ドメインからのメール送信が許されたすべてのサーバーをリスト化した DNS TXT レコードの一種です。
```
このほうが正しい？

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +ドメインと結び付る SPF は1つだけ許可されます。（[RFC4408](https://datatracker.ietf.org/doc/html/rfc4408)）
```suggestion
ドメインと結びつける SPF は1つだけ許可されます。（[RFC4408](https://datatracker.ietf.org/doc/html/rfc4408)）
```
ここの RFC4408 が何なのかわからないので説明がほしいです。

2024-10-20 04:37 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +### SPF 作成
作成手順というよりは、 SPF レコードの中身の説明でしょうか？

2024-10-21 04:03 UTC, Lee-juNu commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +ドメインと結び付る SPF は1つだけ許可されます。（[RFC4408](https://datatracker.ietf.org/doc/html/rfc4408)）
こちらは削除しておきます。 RFC4408を引用しようと付けたものですが、下記の引用するところでも使われているためそちらを修正します。

2024-10-22 00:04 UTC, Lee-juNu commented
@junya-gera 
修正完了しました。ご確認いただけますでしょうか

2024-10-22 12:35 UTC, junya-gera reviewed
追加でコメント入れています。

2024-10-22 12:35 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +本来の TXT レコードは人が読めるノートを入力する用途だったらしいです。昔の TXT レコードはコーディングするときのコメントみたいな説明を目的としていたイメージですね。
英語では note でメモの意味ですが日本語で「ノートを入力する」とはあまり言わないので、他の言葉がいいと思います。

2024-10-22 12:35 UTC, junya-gera commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +申し訳ありません、DMARC レコードの説明が不足していました。簡潔に説明を追加します。
この1文はいりますかね？

2024-10-22 14:05 UTC, Ryotaro49 requested changes, later dismissed
DNS レコードについて知れるいい記事だと思います！
詳しく知らない部分だったので、勉強になりました！
気になったところコメントしてます。

2024-10-22 14:05 UTC, Ryotaro49 commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +最近、メールサーバーについて学んでいるリリです。DNS レコードを触りながら学んだ内容を整理するために、ブログ記事として書いてみました。
DNS を知っていることが前提となっているので、DNS の知識があることを前提とするか、DNS についての軽い説明があったほうが読みやすいかと思いました。

2024-10-22 14:05 UTC, Ryotaro49 commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +  - `v=DKIM1` : DKIM レコードのバージョンを示します。必須です。
```suggestion
  - `v=DKIM1` : DKIM レコードのバージョンを示します。(必須)
```
必須の書き方に揺らぎがあるので、どちらかに統一した方が良いと思います。

2024-10-22 14:05 UTC, Ryotaro49 commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `+all` : 列挙されなくても許容する
ここら辺の文章、「。」で終わらせた方が良いと思います。

2024-10-24 01:01 UTC, Lee-juNu commented
@Ryotaro49 @junya-gera 
修正完了しました。ご確認いただけますでしょうか

2024-10-24 05:04 UTC, kenzauros reviewed
記事の目的をはっきりさせたほうがいいです。

SPF, DKIM, DMARC の違いを説明するのか、それぞれの TXT レコードの設定方法を説明するのか。どちらかというと後者のほうが近いと思いますが、それにしては各レコードの内容の説明が少ない気がしました。

2024-10-24 05:04 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `aspf=s` : SPF の判定を厳格にします。
これは説明としてはあっていますが、どういうオプションがあるのかわかりません。

あと、p については最初から quarantine にすると届いていたメールが届かなくなったりする可能性があり、段階的な設定が推奨されています。
そのあたりも含めて書くとこの記事の有用性があがると思います。

2024-10-24 05:04 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- **本文** : DKIM レコードの内容。以下のように構成されます。
SPF や DMARC はわかりやすいですが、 DKIM の場合、この値がどう決まるのか（どんな値を設定すべきなのか）がわからない気がします。

2024-10-24 05:04 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- **名称** : DKIM レコードの名前。この例では `big-email._domainkey.example.com` となっており、`big-email` はセレクター、`_domainkey` は固定のプレフィックスです。
なぜ `big-email` ？このセレクターの説明がないので、実際に何の値を設定するのか？がわからない。

2024-10-27 23:45 UTC, Lee-juNu commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- **名称** : DKIM レコードの名前。この例では `big-email._domainkey.example.com` となっており、`big-email` はセレクター、`_domainkey` は固定のプレフィックスです。
そうですね、big-email は CloudFlare から引用するときにそのまま持ってきたせいです。修正してセレクターに関する説明を追加しておきます。

2024-10-31 03:31 UTC, Lee-juNu reviewed
@kenzarous DKIM,DMARC の内容を補充しました。ご確認いただけますでしょうか？

2024-10-31 23:56 UTC, kenzauros reviewed
日本語表現の部分が多いですが、いくらか改善してはどうでしょう。

GPT の出力そのままかな？と思える表現が散在しているので、 GPT を使うのはいいですが、そのままの表現を使うのは避けましょう。

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> + 最近メールサーバーを初めて調べながら理解する目的として書いたブログ記事です。"
```suggestion
description: "DNS レコードの基本であるSPF、DKIM、DMARCについて解説しています。最近メールサーバーについて初めてちゃんと調べたので、理解を深めるために記事にしました。"
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +## DNS TXT レコードとは？
この記事は「DNS レコード」の話をしているんですが、そもそも DNS レコードは「手段」であって、「目的」ではないので、「SPF, DKIM, DMARC の目的」＝「メールの送信者認証」の話に触れたほうがいいです。


```suggestion
## SPF, DKIM, DMARC とは？

（送信者認証の説明）

## DNS TXT レコードとは？
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +本来、TXT レコードはドメインに関する情報や管理者の連絡先などを記載する目的で使用されていました。昔の TXT レコードはコーディングするときのコメントみたいな説明を目的としていたイメージですね。
```suggestion
もともと、TXT レコードはドメインに関する情報や管理者の連絡先などを記載する目的で使用されていました。コーディングするときのコメントのようなイメージですね。
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `v=spf1` ：SPF レコードとドメインに知らせます。（必須）
シンプルな箇条書きには「。」はなくてもいいです。

```suggestion
- `v=spf1` ：SPF レコードであることを明示します（必須）
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `ip4:192.0.2.0` : 承認する IP アドレス。（複数定義可能）
```suggestion
- `ip4:192.0.2.0` : 承認するメール送信元の IP アドレス（複数定義可能）
```

あと、どうせなので `a` や `mx` もあったほうがいいと思います。

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `include:examplesender.mail` : 第三者組織がこのドメインに代わってメールを送信できる DNS アドレス。（複数定義可能）
```suggestion
- `include:examplesender.mail` : 第三者組織のメール送信元 DNS アドレス（複数定義可能）
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +- `+all` : 列挙されなくても許容する。
```suggestion
- `-all` : 列挙した以外の送信元を拒否する
- `~all` : 列挙した以外の送信元を許容するが、不審なメールとして扱う
- `+all` : 列挙した以外の送信元も許容する
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +その方式ではメールにデジタル署名を追加し、受信メールが送信ドメインから許可された送信者によって送信されたものであることを確認できる機能です。
```suggestion
この方式ではメールにデジタル署名を追加し、受信メールが送信ドメインから許可された送信者によって送信されたものであることを確認できます。
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +DKIM ヘッダーは、電子メールに挿入される数あるヘッダーの1つです。ほとんどのメールアプリケーションでは、ユーザーが特定のオプションを選択しない限り、ヘッダーは表示されません。
これって GPT の台詞ですか？この記事の説明としては、少し違和感があるので。

```suggestion
DKIM ヘッダーは、電子メールに挿入される数あるヘッダーの1つです。ほとんどのメールアプリケーションでは、ユーザーが特定のオプションを選択しない限り、ヘッダーは表示されません。
```

2024-10-31 23:56 UTC, kenzauros commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +メールサーバー移行の件を聞いてメールサーバーを一度見てみたいと思いました。案件をもらった後に調べている途中一番多く触れたのはこの DNS レコードでした。まだ知らないパソコンの知識を学ぶことは楽しいですね。また別の知識を持ってきます。
「メールサーバー移行の件を聞いて」は、記事の読者には唐突すぎるので、以下のようにしては。

```suggestion
メールサーバー移行の案件があり、送信者認証について調べる機会がありました。避けて通れないのは、この DNS レコードでした。

まだ知らないパソコンの知識を学ぶことは楽しいですね。また次の知識を紹介するのが楽しみです。
```

2024-11-01 00:11 UTC, Lee-juNu commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +DKIM ヘッダーは、電子メールに挿入される数あるヘッダーの1つです。ほとんどのメールアプリケーションでは、ユーザーが特定のオプションを選択しない限り、ヘッダーは表示されません。
GPT からもらって返事を少し修正したものでした。なぜメールに表示されてないか書いておくべきかなと思いました。

2024-11-01 00:15 UTC, Lee-juNu commented on Lee-juNu/2024/dns-txt-record-with-spf-dkim-dmarc/index.md
> +DKIM ヘッダーは、電子メールに挿入される数あるヘッダーの1つです。ほとんどのメールアプリケーションでは、ユーザーが特定のオプションを選択しない限り、ヘッダーは表示されません。
あ、すみません。ここ　GPT ではなく CloudFlare で見て自分で修正した方でした

2024-11-18 03:04 UTC, merged